version: 2

name: Py_xDH
type: sphinx

sphinx:
  configuration: docs/conf.py

build:
  image: latest

python:
  version: 3.7
  install:
    - requirements: docs/requirements.yml
  system_packages: true

formats: [htmlzip]
