version: 2

sphinx:
  configuration: docs/source/conf.py

submodules:
  include: all

build:
  image: latest

python:
  version: 3.7
  install:
    - requirements: docs/requirements.yml
  system_packages: true

formats: [htmlzip]
