version: 2

sphinx:
  configuration: docs/source/conf.py

build:
  image: ubuntu-22.04
  apt_packages:
    - pandoc

python:
  version: 3.7
  install:
    - requirements: docs/requirements.yml

formats: [htmlzip]
