language: python
python:
    - "3.7"

os: linux
dist: xenial
cache: pip
before_install:
    - export PYTHONPATH=$TRAVIS_BUILD_DIR:$PYTHONPATH
    - cp $TRAVIS_BUILD_DIR/.pyscf_conf.py ~/.pyscf_conf.py
    - pip install -r requirements.txt

matrix:
  include:
    - name: pyxdh
      script:
        - cd $TRAVIS_BUILD_DIR
        - export LOGLEVEL=2
        - export OPENBLAS_NUM_THREADS=4
        - export MKL_NUM_THREADS=4
        - pytest pyxdh --disable-warnings --cov=pyxdh --cov-config=.coveragerc

deploy:
  provider: pypi
  user: ajz34
  password: YouCantSee233
  distributions: "sdist bdist_wheel"
  on:
    tags: true
